# La Base de Données PostgreSQL
databases:
  - name: tonnine-db
    plan: free
    region: frankfurt

services:
  # Le Backend Laravel
  - type: web
    name: tonnine-benin-backend
    env: docker
    plan: free
    region: frankfurt
    healthCheckPath: /api/v1/users/leaderboard
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: tonnine-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: tonnine-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: tonnine-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: tonnine-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: tonnine-db
          property: password
      - key: LOG_CHANNEL
        value: errorlog
      - key: APP_URL
        value: https://tonnine-benin-backend.onrender.com
      
      # === Email SMTP (pour envoyer les OTP) ===
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp-relay.brevo.com
      - key: MAIL_PORT
        value: "2525"
      - key: MAIL_USERNAME
        value: a0650d001@smtp-brevo.com
      - key: MAIL_PASSWORD
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: mourchidolawale@gmail.com
      - key: MAIL_FROM_NAME
        value: "TontineChain"

      # === FEDAPAY ===
      - key: FEDAPAY_API_KEY
        value: sk_sandbox_wyJZtZjU5uyd9KbFqjyPbksj
      - key: FEDAPAY_PUBLIC_KEY
        value: pk_sandbox_QSs3-34T7hDjsAVcnYBViUhz
      - key: FEDAPAY_WEBHOOK_SECRET
        value: wh_sandbox_STo2s4w_sl_SN1sDtoibvjhk
      - key: FEDAPAY_ENV
        value: sandbox

      # === INFOBIP ===
      - key: INFOBIP_API_KEY
        value: 2b97febce9e8a0353a21fb91f74e07bd-9ad39504-b83e-455c-adb9-f5e319af1392
      - key: INFOBIP_BASE_URL
        value: https://d85xdg.api.infobip.com
      - key: WHATSAPP_SENDER_NUMBER
        value: "447860088970"

      # === BLOCKCHAIN ===
      - key: POLYGON_RPC_URL
        value: https://polygon-mainnet.infura.io/v3/6e201afd04aa4ae7a4d6eda9a2488250
      - key: RELAYER_PRIVATE_KEY
        value: 0x4f3e2d1c6b5a9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b
      - key: TONTINE_FACTORY_ADDRESS
        value: 0x742d35Cc6634C0532925a3b844Bc454e4438f44e


