services:
  # Le Backend Laravel
  - type: web
    name: tonnine-benin-backend
    env: docker
    plan: free
    region: frankfurt
    healthCheckPath: /api/v1/users/leaderboard
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: tonnine-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: tonnine-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: tonnine-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: tonnine-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: tonnine-db
          property: password
      - key: LOG_CHANNEL
        value: errorlog

# La Base de Données PostgreSQL
databases:
  - name: tonnine-db
    plan: free
    region: frankfurt
